# Basics of TensorFlow

In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\Lukas\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


### creating variables:

In [ ]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

note: all other objects specified by tensorflow are immutable!

to be more specific:
- Constant
- Placeholder
- SparseTensor

are immutable

### creating vectors and matrizes (Tensors):

In [21]:
rank1_tensor = tf.Variable(["test", "Ok"], tf.string)
rank2_tensor = tf.Variable([rank1_tensor,["test", "yes"], ["tesnor", "flow"]], tf.string)
print(str(type(rank2_tensor)) + "\n")
print(rank2_tensor)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>

<tf.Variable 'Variable:0' shape=(3, 2) dtype=string, numpy=
array([[b'test', b'Ok'],
       [b'test', b'yes'],
       [b'tesnor', b'flow']], dtype=object)>


determining the rank of a tensor:

In [12]:
rank = tf.rank(rank2_tensor)
print(rank)
type(rank)

tf.Tensor(2, shape=(), dtype=int32)


tensorflow.python.framework.ops.EagerTensor

shape of a tensor:

In [13]:
print(rank1_tensor.shape)
print(rank2_tensor.shape)

(2,)
(3, 2)


reshaping tensors:

In [23]:
new_tensor = tf.reshape(rank2_tensor, [-1, 6]) # -1 tells tensorflow to calculate the size of the elements in that place
print(new_tensor)

tf.Tensor([[b'test' b'Ok' b'test' b'yes' b'tesnor' b'flow']], shape=(1, 6), dtype=string)


In [29]:
tensor1 = tf.ones([1, 2, 3]) # creating a tensor of only 1s
tensor2 = tf.reshape(tensor1, [2, -1]) # reducing dimensions and calculating remains
tensor3 = tf.reshape(tensor1, [2, 1, 1, 3]) # increasing dimensions

print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[[1. 1. 1.]]]


 [[[1. 1. 1.]]]], shape=(2, 1, 1, 3), dtype=float32)


### creating and using Sessions:

In [36]:
tf.compat.v1.disable_eager_execution()
tensor1 = tf.ones([1, 2, 3])

with tf.compat.v1.Session() as sess:
    tensor1.eval()

# note that Sessions have been remove in tensorflow 2.0. So usage is outdated